---
categories:
  - AnalisaR
  - Ciência de dados
  - Data science
  - Numerical ecology
  - Ecologia numérica
tags:
  - R
  - programação
  - curiosidades R
  - R programming
  - Programação em R
  - Ecology
  - Numerical ecology
  - Ecologia
  - Ecologia numérica
output: 
  html_document:
    theme: darkly
    highlight: breezedark
    toc: true
    toc_depth: 3
    toc_float: true
    colapse: true
    smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Blog AnalisaR**{.tabset .tabset-fade .tabset-pills}

O Blog **AnalisaR** é um espaço em construção permanente para divulgação do R como ferramenta indispensável para: (1) professores que trabalham com ensino de matemática e estatística básica e avançada; (2) para pesquisadores que trabalham com questões que envolvem a coleta e análise de dados, sejam eles provenientes de estudos realizados em campo ou em laboratório; e (3) para todos que se interessam por ciência de dados. O público alvo deste espaço são professores e cientistas de qualquer área de conhecimento, além de todos os apaixonados por programação e análise de dados.

No **AnalisaR** serão postados frequentemente textos sobre temas relacionados a linguagem R e sua aplicação nas diversas etapas envolvidas no desenvolvimento de uma pesquisa. As postagens irão abranger aspectos que vão da elaboração do delineamento amostral, análise dos dados, obtenção e representação gráfica dos resultados até ferramentas para a apresentação textual dos resultados. Tudo isso utilizando a linguagem R de programação.

### [Mas o que o R?](Mas-o-que-é-o-R.html){.tabset}

### [Qual são as vantagens do R?](){.tabset}

#### [AnalisaR](index.html){.tabset}

#### [Portifolio](Portifolio.html){.tabset}

#### [Equipe AnalisaR](Equipe-AnalisaR.html){.tabset}

#### [Contato](Contato.html){.tabset}