---
title: "Blog Analisar"
output: 
  html_document:
    theme: cosmo
    highlight: monochrome
    df_print: kable
    css: styles.css
categories:
  - AnalisaR
  - Ciência de dados
  - Data science
  - Numerical ecology
  - Ecologia numérica
tags:
  - R
  - programação
  - curiosidades R
  - R programming
  - Programação em R
  - Ecology
  - Numerical ecology
  - Ecologia
  - Ecologia numérica
---
# **Blog AnalisaR**{.tabset .tabset-fade .tabset-pills}

O Blog **AnalisaR** é um espaço em construção permanente que traz textos para o aprendizado e o uso da matemática e da estatística para no estudo de fenômenos naturais, em especial os ecológicos. Como ferramenta para aprendizado e utilização da matemática e da estatística será utilizado a linguagem R de programação. Dessa forma, o Blog **AnalisaR** também traz posts sobre como programar em R e como utilizar essa habilidade em seu favor para o aprendizado e aplicação da matemática e da estatística. A programação ferramenta indispensável para (1) professores que trabalham com ensino de matemática e estatística básica e avançada; (2) para pesquisadores que trabalham com questões que envolvem a coleta e análise de dados, sejam eles provenientes de estudos realizados em campo ou em laboratório; e (3) para todos que se interessam por ciência de dados. O público alvo deste espaço são professores e cientistas de qualquer área de conhecimento, embora a ênfase seja dada à ecologia, além de todos os apaixonados por programação e análise de dados.

No **AnalisaR** serão postados frequentemente textos sobre temas relacionados a linguagem R e sua aplicação nas diversas etapas envolvidas no desenvolvimento de uma pesquisa. As postagens irão abranger aspectos que vão da elaboração do delineamento amostral, análise dos dados, obtenção e representação gráfica dos resultados até ferramentas para a apresentação textual dos resultados. Tudo isso utilizando a linguagem R de programação.

### [Mas o que o R?](Mas-o-que-é-o-R.html)

### [Por que devo utilizar o R?]()

### [Cursos Analisar](Cursos.html)

### [Equipe AnalisaR](https://vntborgesjr.github.io/vntborgesjr/)

### [Contato](Contato.html)